### ISSUE TITLE
Clarify advice for PSDs without a consistent slope across the region of interest

### ISSUE THREAD

**Issue by srcole** [voytekresearch/fooof#21]
I'm fitting a PSD of motor cortical ECoG data (same data as issue #20), and it may be a bit unique because it does not have a consistent slope across the frequency range I'm interested in fitting. 

If I fit 1-100Hz, then I end up with a lot of "peaks" to fill in the power above the beta range, since the curve fit is at a much lower power. If I fit 1-40Hz, the peak seems reasonable, but I would have to know to do this, but the slope is pretty meaningless.

It would be really great if fooof was able to recognize if the slope fit is really bad and notify the user that the fit is not good. But I acknowledge that's a really tough problem. I'll try to think of possible ways to handle this.

![image](https://user-images.githubusercontent.com/7298871/29593583-ff44cd82-875f-11e7-8d44-11dbf8ca6b58.png)
![image](https://user-images.githubusercontent.com/7298871/29593589-06d19fda-8760-11e7-9445-fd910d611fa3.png)

**Comment by TomDonoghue** [comment]
HAHAHAHAHAH at August 31st 'okay we're ready to lock in v0.1.

**Comment by TomDonoghue** [comment]
This issue / discussion has been addressed by adding knee fitting options. Closing.
