### ISSUE TITLE
group plotting uses the wrong index when fit with knee

### ISSUE THREAD

**Issue by rdgao** [voytekresearch/fooof#43]
import fooof as ff
fms = ff.FOOOFGroup(verbose=False,bg_use_knee=True)
fms.fit_group(freqs,PSDs, freq_range=(2,100))
fms.plot()

this will take the knee parameters and plot them as slope in the report.

**Comment by TomDonoghue** [comment]
Fixed in last_tweaks branch. Will close with merge.
