### ISSUE TITLE
FAAAAAAAT FOOOF.

### ISSUE THREAD

**Issue by parenthetical-e** [voytekresearch/fooof#57]
Cloning the repo and it's 89.32 Mb! Is the release version that big? This thing fits a line(s) and finds some peaks. I mean I'm glad we've got tests/notebooks but there has to be way to trim it down.

**Comment by TomDonoghue** [comment]
That's all the tutorials (presumably). As far I understand / plan it, they won't be in release version version, that gets uploaded to pip, etc.

The actual release code base (fooof folder) is <1 Mb, I think. 
The tests generate their own data to run, so their is no data packaged with them. 

Exactly how we plan for people to get the tutorials, if they want them, is not totally clear though actually. What's the canonical way for people to get tutorial materials?

**Comment by TomDonoghue** [comment]
@parenthetical-e 
Also, sidenote: code-base is sort-of fractured right now, but if you want the most up to date code to play with, go with 'last_tweaks_....' branch (not master), but note that tutorial and PyPi stuff is separate ('tutorials' & 'release' branches, respectively).

**Comment by parenthetical-e** [comment]
There isn’t a good self-contained way besides a binder link from the readme.

The best way is probably to create a simple website for FOOOF and link/host html versions directly, and give instructions for cloning/getting to the tutorials in a runable way. Including binder links too obv.

**Comment by TomDonoghue** [comment]
I updated the note in #51 about tutorial access to include a note about a website etc, so I'm going to close this issue now, as I think there's nothing separate requiring action here.
