### ISSUE TITLE
elegant fail if scipy<19

### ISSUE THREAD

**Issue by voytek** [voytekresearch/fooof#58]
If scipy version isn't 19+ fooof fails in... non-obvious... ways. Just spent 10 minutes troubleshooting before I had an "ooooh wait" moment.

**Comment by TomDonoghue** [comment]
This won't happen if you install it "correctly" (through pip) once available, as the minimum version is enforced there. 

We could add a check, which would only really be relevant for people who clone the repo, and add to path without running pip (not recommended), and perhaps those who run pip development mode, but it is also reasonable to expect people doing custom installs to check and enforce requirements.

**Comment by TomDonoghue** [comment]
@voytek : so do you want me to add an explicit check for this?

@parenthetical-e : any thought on conventions here?

**Comment by voytek** [comment]
It shouldn't be needed if installed, as you say. We're very clear in requirements.txt and setup. HOWEVER I've already run into this with one user who was running FOOOF wherein they had scipy 18.x and it was failing in a very inelegant and non-transparent way.

It's very simple to add an explicit check and clear warning, which seems nice in terms of being thorough.

**Comment by TomDonoghue** [comment]
I sorta don't like adding it, as it's an edge case of early development that this appeared in that user (and so it shouldn't come up again, making the check redundant and counter to general dependency practice). 

That said, it's easy enough, so I've added it in commit dd1b13e5ccfcc09e83b86e14d3486625d14fa161
