### ISSUE TITLE
Support for Matlab users

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/fooof#64]
Many people who might be interested in this tool are primarily Matlab users. We should make it as easy as possible for them to integrate FOOOF into their pipelines. 

Options (non-exclusive):
- Would could have a demo notebook / script, that serves a template for the minimum required to load PSDs (from a mat file), run FOOOF, and save them back out, for further analysis back in Matlab. 
Edit: done, in fooof_mat
- To assist with above, we could add a FOOOF save option to save out to .mat? (This would be useful if loading the default json files is not so good / straightforward from Matlab).
Edit: not really needed, since Matlab can load the json files.
- Is there for simple Matlab code we can write for loading and parsing FOOOF result files (jsonlines)?
Edit: yep. Added in fooof_mat. 
- Can we add a Matlab wrapper? How easy is it to call python from Matlab? Can we avoid people having to move to python entirely? (Didn't pacmat do this?  cc @srcole). 
Edit: done, in fooof_mat.

**Comment by srcole** [comment]
Yeah, MATLAB wrapper can be pretty simple. For example, the matlab script to call the pacpy function pac_glm is:

```
function pac = pac_glm(lo, hi, f_lo, f_hi, fs)

    % Convert inputs
    lo = py.numpy.array(lo);
    hi = py.numpy.array(hi);
    f_lo = py.tuple(f_lo);
    f_hi = py.tuple(f_hi);

    % Call python
    pac = py.pacpy.pac.glm(lo, hi, f_lo, f_hi, fs);
end
```

Basically, you just need to convert the matlab variables into python variables. And do the same for the output if it's nontrivial (the 'pac' output variable was just a float).

But downside to this is that it requires the MATLAB user to still get python installed and set up to use FOOOF. Which may be nontrivial if they really only have used MATLAB.

**Comment by voytek** [comment]
It would be relatively easy (an undergrad could do it) to convert the core algorithm to matlab. No nice plotting, or FOOOFgroup tools.

My only concern is the stability of results across platforms. The fitting algorithms introduce the possibility for differences between platforms that would explicitly need to be tested.

**Comment by TomDonoghue** [comment]
I have more detailed thoughts on this, but as a summary: all of the NOPE.

**Comment by voytek** [comment]
Just for the record, we'll go with the wrapper and leave it at that.

**Comment by dlevenstein** [comment]
Hey guys, any further thoughts/progress on a matlab-friendly FOOFlite? 
The power spectrum slope has suddenly become very relevant in one of my projects... but our lab is still in matlab. Figured it would be better to use your established method than start from scratch if possible.

**Comment by voytek** [comment]
For now, it's best to just save mat files of the data, feed those in to fooof, and then export the slope fits (or whatever other features) to pull back into matlab.

**Comment by TomDonoghue** [comment]
@dlevenstein 

We are not currently planning a re-implementation of the algorithm in Matlab, but I finally got around to making the support materials / functions for using FOOOF from Matlab - either as a wrapper from Matlab directly, or in a workflow that has you efficiently in and out of Python, as part of a Matlab pipeline. 

All this stuff is now available here:
http://github.com/voytekresearch/fooof_mat

Note: this is all brand new - so if you do test it out, please let us know if it all works, and make any comments / suggestions, etc.

**Comment by dlevenstein** [comment]
Thanks guys! I'll let you know how it goes.
Dan

**Comment by TomDonoghue** [comment]
@dlevenstein Sounds good!
If you do have any comments, please open issues over at fooof_mat:
http://github.com/voytekresearch/fooof_mat

@ everyone: 
Since we covered the points of this issue, and related stuff has been moved, I'm going to close this issue. Any further discussion should be over at fooof_mat.
