### ISSUE TITLE
FOOOFGroup.load() automatically appends json

### ISSUE THREAD

**Issue by srcole** [voytekresearch/fooof#65]
I'm using the `glob` library to find all the FOOOFGroup .json files I want to load. glob returns full file paths, e.g. '/gh/data/megshape/fooof/102816_fooof_vertex.json'

However, FOOOFGroup.load('/gh/data/megshape/fooof/102816_fooof_vertex.json') returns an error because it is trying to load '/gh/data/megshape/fooof/102816_fooof_vertex.json.json' (extra .json).

So, ideally FOOOF would be able to recognize that the filename that I am passing into the load function already ends in .json.

**Comment by srcole** [comment]
Similar "issue" for FOOOFGroup.save()
As a user, I expect to have to declare the file extension

**Comment by TomDonoghue** [comment]
Thanks for the heads up - this was bad design in the file IO. Fixed now to check for file names, only append if missing (so it will work with strings with or without file extensions).
