### ISSUE TITLE
FOOOFGroup results as dataframe

### ISSUE THREAD

**Issue by srcole** [voytekresearch/fooof#68]
Right now, FOOOFGroup saves to a .json file where each line is a FOOOFResult object. However, the group-wide oscillation information would be more easily accessible as a dataframe, in which each row is a peak, and the columns are: psd_index, center frequency, amp, bandwidth, etc.

So, there could be a function that converts the list of FOOOFResults (FOOOFGroup.group_results) into this dataframe.

As Tom mentioned IRL, this will add a dependency for pandas. But, that's common and why we safe_import.

**Comment by TomDonoghue** [comment]
As discussed in lab - we're prioritizing being light on dependencies, and with the updated to 'get_all_data', it's straightforward to convert to a df externally, without us having to support it. I'm wary of adding more dependencies that open us up to a ballooning infrastructure, as opposed to the tight & clean - fit model, get the results: now it's up to you what to do with them.

We could revisit this later, but for now, let's not add it.
