### ISSUE TITLE
inf/NaN array while trying to curve_fit

### ISSUE THREAD

**Issue by dvwz** [voytekresearch/fooof#71]
After successfully running the tutorials, I'm trying to pass some computed spectra from experimental data through the FOOOFGroup methods, and got the following error:
```
  File "run_fooof.py", line 18, in <module>
    fg.fit(freqs, spectra_pre)
  File "/data/purdongp/users/dwzhou/code/fooof/fooof/group.py", line 141, in fit
    self._fit(power_spectrum=power_spectrum)
  File "/data/purdongp/users/dwzhou/code/fooof/fooof/group.py", line 287, in _fit
    super().fit(*args, **kwargs)
  File "/data/purdongp/users/dwzhou/code/fooof/fooof/fit.py", line 316, in fit
    self.background_params_ = self._robust_bg_fit(self.freqs, self.power_spectrum)
  File "/data/purdongp/users/dwzhou/code/fooof/fooof/fit.py", line 527, in _robust_bg_fit
    popt = self._simple_bg_fit(freqs, power_spectrum)
  File "/data/purdongp/users/dwzhou/code/fooof/fooof/fit.py", line 505, in _simple_bg_fit
    maxfev=5000, bounds=self._bg_bounds)
  File "/PHShome/dwz0/.conda/envs/py36/lib/python3.6/site-packages/scipy/optimize/minpack.py", line 701, in curve_fit
    ydata = np.asarray_chkfinite(ydata)
  File "/PHShome/dwz0/.conda/envs/py36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```
I checked my input arrays with assertions for infs and NaNs, but they all passed. I noticed the comment about negative values of b in the source code where curve_fit is called. (Maybe not the same issue.) My input spectra have some negative values in them, so I added to the entire data to remove negative values and no errors appeared. Since spectra in log10 scale (mine are in dB) should be able to take on negative values, perhaps something should be done about curve_fit.

EDIT: There are other issues that come up with spectra containing 0 or 1 values that don't have to do with curve_fit.

EDIT2: I may have misunderstood the specifications for the input spectra. I thought they were supposed to be in log10 scale, so I precomputed my spectra in dB and then passed them. Looking at the plotted results, it seems like FOOOF took another log10 of them. So instead I input raw power spectra, and it's fine. Is this right?

**Comment by dvwz** [comment]
There are other issues that come up with spectra containing 0 or 1 values that don't have to do with curve_fit.

**Comment by TomDonoghue** [comment]
Yes, the inputs to FOOOF must be frequencies and power values, both in linear space (not logged). 

Internally it does use log10 power values, but it computes the logs for this internally. It does not check the inputs explicitly for log-status, so if you pass in logged values, you are liable to get errors such as inf / NaNs, etc. 

Hopefully passing in non-logged data makes it all work - please let me know if this doesn't seem to fix it / if anything else is up.

**Comment by dvwz** [comment]
Yep, it all works after I realized that they should all be in linear space.
