### ISSUE TITLE
equidistant frequency fitting in log-space

### ISSUE THREAD

**Issue by rdgao** [voytekresearch/fooof#72]
PSDs are currently fit in log-log, which means it weighs higher frequency much more so than low frequencies, because evenly spaced frequencies in linear scale congregate in high frequencies in log scale. 

Practically, this is not a huge concern. It might even give us the desired effect of ignoring non-1/f stuff in the low frequencies. But it's not immediately obvious that this is the way it currently works to the user. For 1.0, perhaps a note stating the above is sufficient. For future versions, the user would ideally get an option to fit equidistant frequencies in **log space**, or something that de-weighs higher frequencies (weighted regression).

**Comment by TomDonoghue** [comment]
Except that FOOOF doesn't actually fit in log-log...? It fits semi-log: linear-freqs, log power.

So though I agree in principal, this is irrelevant, so unless I'm missing something here, we can close this.

**Comment by rdgao** [comment]
wow. That was a complete brainfart seeing how that was the one line of code I wrote...

In that case, no note to the user is necessary since presumably no references to linear-fitting in log-log  will be made when you describe the function form. 

The technical question remains, however, since fitting the Lorentzian (no knee) in semilog is mathematically equivalent to fitting a line in log-log (it still uses every frequency point). Just to clarify, the specific issue is not from fitting in log-log, but in using linearly-spaced frequency points. 

In both situations, the error between 10-20Hz weighs just as much as the error between 80-90Hz, which is potentially undesirable, given our a priori knowledge about brain PSDs.

**Comment by TomDonoghue** [comment]
Okay - yeah, I see what you're getting at, and a discussion of frequency spacing is definitely warranted for future iterations. 

For clarity, I am going to re-open an issue for that specifically, since this thread is a bit confusing wrt the point it's making.

**Comment by rdgao** [comment]
perfect, sounds good!
