### ISSUE TITLE
Missing text in Tutorial 05

### ISSUE THREAD

**Issue by voytek** [voytekresearch/fooof#78]
"- Interpreting the fit results when using knee fits is not"

Is not what?!?!

**Comment by TomDonoghue** [comment]
Oh. hahaha - oops. 

I think I was trying to figure out to gently say 'we don't much a lot of idea about the knee - be careful' - in particular it influences how you interpret the slope value (given that the slope value, by itself, reflects some region w.r.t. the knee parameter). 

I'll fix this up when I run back through the tutorials.

**Comment by TomDonoghue** [comment]
Okay, finished up that half thought sentence and slight fixes up on 05.

Should be good, @rdgao maybe you wanna eyeball the knee notes and make sure the are in line with what you think? Pushed to the 'terms' branch, tutorial 05. 

Otherwise, this should be good to close.
