### ISSUE TITLE
Add Contributing file

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/fooof#80]
We're starting to get some interest in adding / submitting to the repo, etc. We should add a Contributing.md file, that outlines preferred mechanisms to do so, as well as a CodeOfConduct (I think this can be a copy of some standard one that basically covers 'don't be an ass').

**Comment by GrantRVD** [comment]
`npm install -g covgen` will install the [Contributor Covenant](https://www.contributor-covenant.org/), which is the standard for a lot of open software codes of conduct. Afterward, running `covgen VoytekResearch@gmail.com` will install it into the project and embed the appropriate contact email. Additions and modifications specific to the Voytek Lab are encouraged.

For `Contributing.md`, I always like to refer to the [Mozilla Working Open Workshop](https://mozillascience.github.io/WOW-2017/contributing/) materials. Full disclosure: I interact a lot with Mozilla, so I'm definitely biased.

**Comment by TomDonoghue** [comment]
Thanks for the notes @GrantRVD 

Code of Conduct and Contributing Guide added.
