### ISSUE TITLE
Add some kind of convenience function for FOOOFing 3D collections of PSDs

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/fooof#83]
In the vein of adding general functionality, that otherwise people are constantly re-writting, this is a code piece I find myself replicating a lot, in which I have a 3D matrix of PSDs across epochs & channels, as [n_epochs, n_chs, n_freqs]:

```
fgs = []
for ep_psds in all_psds:
    fg.fit(freqs, ep_psds)
    fgs.append(fg.copy())
```

This results in a list of FOOOFGroup objects, and so maintains information about epoch and channel of provenance, for each fit. 

The simplest, and I think perhaps best, addition for dealing with this common case is just adding a function that literally does the process above, return a list of FOOOFGroup objects. The alternative is an update of the FOOOFGroup object so that it takes 3D inputs as well, or another object that inherits from FOOOFGroup to do so (FOOOFGroupGroup?).

Note: there is a recent addition of concatenation functions, to collapse across FOOOFGroups, which is related to this.

**Comment by parenthetical-e** [comment]
What is wrong with having to write a simple for three line loop?

Not all usage patterns need APIs. I'd argue (again :) that very few do.

**Comment by TomDonoghue** [comment]
I don't like excessively re-writing, or copy-pasting code, and now I'm starting to do across across multiple tasks / conditions, I end up copying this loop multiple times in a row, and it starts to look a lot like the prototypical 'this should be a function'. 

I agree on limiting API extensions, and in this case the idea being adding a function is a minimal, but I think quite useful (it's a pretty general use case) addition. To limit the API, I wouldn't change/add objects (FOOOFGroupGroup was supposed to be a joke :))

Literally this function (could have a better name):
```
def fooof_3D(fg, psds)
  fgs = []
  for ep_psds in psds:
      fg.fit(freqs, ep_psds)
      fgs.append(fg.copy())

  return fgs
```

**Comment by parenthetical-e** [comment]
:Shrug:

We've philosophical differences. 

In your own judgement, Tom.

**Comment by TomDonoghue** [comment]
After being annoyed at re-writing this code segment again, I added this in:

function: fit_fooof_group_3d, lives in fooof.group, but is accessible from top level (from fooof import fit_fooof_group_3d). 

I'm not a huge fan of the function name (suggestions welcome), but I think it's a useful thing to have, so it's in there now.
