### ISSUE TITLE
FOOOFGroup fails silently if passed a list of spectra

### ISSUE THREAD

**Issue by sydney-smith** [voytekresearch/fooof#86]
Because FG checks for arrays as a condition for adding data, if passed improper data (such as a list), it will not add any data, and then not fit a model when called as fit, silently doing nothing. 

FG.fit should catch if data is wrong format (such as a list), and/or throw a warning / error if no data is available to fit.

**Comment by TomDonoghue** [comment]
Fixed: Updated procedure for adding & preparing data - consolidates data checking all into the '_prepare_data' method, including a new check that data are lists, and does this before anything that presumes data are arrays, to ensure informative errors are used.
